### ISSUE TITLE
README addition 

### ISSUE THREAD

**Issue by Lakhankumawat** [SamarpanCoder2002/Food-Delivery-App-Clone#1]
Hi @SamarpanCoder2002  please add some images of appearance of your app design so the newcomer like me can get idea how it looks before cloning repo. You can add it to README.md just drag and drop . Efforts appreciated .

**Comment by SamarpanCoder2002** [comment]
> Hi @SamarpanCoder2002 please add some images of appearance of your app design so the newcomer like me can get idea how it looks before cloning repo. You can add it to README.md just drag and drop . Efforts appreciated .

Yah..actually I am still working on that not completed yet...I will add app screen images in Readme soon...thanks for inform

**Comment by SamarpanCoder2002** [comment]
@Lakhankumawat REadme properly added with pic...Pls take a look..thank you

**Comment by Lakhankumawat** [comment]
Looks Great , I can't believe you made your second app within a week after that your chatting app . It look way way more functional than what i make currently . Design seems nice ....😅

**Comment by Lakhankumawat** [comment]
If you followed any tutorial then please like to mention .😃

**Comment by SamarpanCoder2002** [comment]
> If you followed any tutorial then please like to mention .😃

No, I did not follow any tutorials sorry...and that app is not fully functional like my previous chatting app Generation... I work at design and with REST API Integration to practice.....  I only follow flutter documentation to work with REST API.

Thanks for your kind words.
